### ISSUE TITLE
二级页面右边有按钮，在pop二级页面一小半时，抬起手指，出现右按钮与左边按钮重叠

### ISSUE THREAD

**Issue by maoni404** [spicyShrimp/UINavigation-SXFixSpace#12]
二级页面右边有按钮，在pop二级页面一小半时，抬起手指，出现右按钮与左边按钮重叠，如下图:
![img_1657bd78fb1b-1](https://user-images.githubusercontent.com/15757665/40470873-64e4a416-5f67-11e8-9e4b-1f6acb06ccc7.jpeg)

**Comment by spicyShrimp** [comment]
设置导航栏的按钮写在viewWillAppeare中
