### ISSUE TITLE
ios 11以下 左边往右偏移了位置 右边往左偏移了位置

### ISSUE THREAD

**Issue by ArthurCL** [spicyShrimp/UINavigation-SXFixSpace#14]
UIBarButtonItem * backItem = [UIBarButtonItem itemWithTarget:nil action:nil image:[UIImage imageNamed:@"back_Image"]];
    self.navigationItem.leftBarButtonItem = backItem;
这是创建按钮的代码 iOS11的位置正常，   11以下 我用iOS 9 的试了下 位置就不正常了

**Comment by spicyShrimp** [comment]
已修复,之前改出的问题, 最新版1.0.6
