### ISSUE TITLE
新版的这个如果是文字的话 间距太小了基本都在边上了

### ISSUE THREAD

**Issue by deanli08** [spicyShrimp/UINavigation-SXFixSpace#17]
iPhone6  ios 9
![simulator screen shot - iphone 6 - 2018-07-30 at 17 59 35](https://user-images.githubusercontent.com/11403708/43391111-5d757a4e-9422-11e8-98aa-6d74b71c0b8d.png)
iPhone6 ios 11
![simulator screen shot - iphone 6 - 2018-07-30 at 18 00 49](https://user-images.githubusercontent.com/11403708/43391169-8a38874c-9422-11e8-9468-747fa5174cce.png)

**Comment by spicyShrimp** [comment]
添加了可控制width的属性
@property(nonatomic, assign)CGFloat sx_defaultFixSpace;//item距离两端的间距,默认为0(iOS11及之后有效)
@property(nonatomic, assign)CGFloat sx_fixedSpaceWidth;//iOS11之前调整间距,默认为-20,(iOS11之前有效)
@property(nonatomic, assign)BOOL sx_disableFixSpace;//是否禁止使用修正,默认为NO
