### ISSUE TITLE
iOS10与iOS11距离左右的间距不一样

### ISSUE THREAD

**Issue by QuintGao** [spicyShrimp/UINavigation-SXFixSpace#2]
测试环境：模拟器

iOS10.3.1中，左边距离是4
iOS11.0，左边距离是8

**Comment by spicyShrimp** [comment]
这个你可以调整的ios10的情况下我在偏移中是-20的,没有仔细调整,你看着修改下这个数,把20改成合适的大小,比如16

**Comment by spicyShrimp** [comment]
-(void)sx_setLeftBarButtonItems:(NSArray<UIBarButtonItem *> *)leftBarButtonItems {
    NSMutableArray *items = [NSMutableArray arrayWithObject:[self fixedSpaceWithWidth:sx_defaultFixSpace-20]];//可修正iOS11之前的偏移
    [items addObjectsFromArray:leftBarButtonItems];
    [self sx_setLeftBarButtonItems:items];
}
调整这个20,修改成合适的数字,即可

**Comment by QuintGao** [comment]
已通过调整sx_defaultFixSpace解决。但是又发现了其他的bug，在iOS10.3.1中，弹出UIImagePickerController时取消按钮不见了，应该是你设置左右item为nil时导致的

**Comment by QuintGao** [comment]
[self sx_setLeftBarButtonItem:leftBarButtonItem];
[self setLeftBarButtonItems:nil];
把这两句调整下顺序就好了

**Comment by spicyShrimp** [comment]
是的,之前没有注意,只是根据判断写的,没有实际跳转查看,谢谢提醒,已经修正

**Comment by spicyShrimp** [comment]
更新了按钮的显示逻辑
