### ISSUE TITLE
迫切希望加个hook黑名单功能

### ISSUE THREAD

**Issue by wang0458** [spicyShrimp/UINavigation-SXFixSpace#24]
感觉侵入性太大，会导致一些有导航栏的第三方库受到牵连，影响三方库的导航显示，能否加个hook黑名单功能，加入黑名单的类不受这个category的影响

**Comment by spicyShrimp** [comment]
在需要的地方@property (nonatomic, assign) BOOL sx_disableFixSpace;    //是否禁止使用修正,默认为NO

**Comment by wang0458** [comment]
OK，按照您的方式解决了，没仔细看这个属性sx_disableFixSpace，谢谢大神
