### ISSUE TITLE
titleView位置覆盖了rightBarButtonItem的位置时，titleView有个向右伸展的动画，怎么去掉？

### ISSUE THREAD

**Issue by li-chenglong** [spicyShrimp/UINavigation-SXFixSpace#3]

**Comment by spicyShrimp** [comment]
在你自定义的titleView中重写intrinsicContentSize 的Get 方法,如下：
- (CGSize)intrinsicContentSize{
return UILayoutFittingExpandedSize;
}
如果设置了固定的titleview的大小宽度，
- (CGSize)intrinsicContentSize{
return CGSizeMake(200, 30);
}
