### ISSUE TITLE
iOS11.2 popViewControllerAnimated:NO 时，UINavigationBar不调用layoutSubviews

### ISSUE THREAD

**Issue by li-chenglong** [spicyShrimp/UINavigation-SXFixSpace#4]
iOS11.2 popViewControllerAnimated:NO 时，UINavigationBar不调用layoutSubviews

**Comment by shengyangyu** [comment]
确实不会调用了，包括pushViewControllerAnimated:NO 时，这种情况如果能主动调用就好了，不过这些场景都不是很多，popToRootViewController确又是会调用的。

**Comment by spicyShrimp** [comment]
动画为NO的情况下,确实不会主动调用,问题已经修复

**Comment by shengyangyu** [comment]
请问sx_popNavigationItemAnimated这个方法有什么用吗？

**Comment by spicyShrimp** [comment]
拦截系统原来的pop方法 在动画为NO的时候强制调用layoutSubviews
