### ISSUE TITLE
leftBarButtonItem 间距设置无效

### ISSUE THREAD

**Issue by liuxingIphone** [spicyShrimp/UINavigation-SXFixSpace#5]
leftBarButtonItem 间距设置无效，right正常呀，又遇到吗？

**Comment by spicyShrimp** [comment]
暂时未遇到  你可以把你的具体现象描述出来  或者写个demo给我

**Comment by jueying-xiangfeng** [comment]
我也遇到了，leftBarButtonItem 设置后在iOS11.2 的系统上左面还是有20个像素的偏移，就用的down下来的项目跑的，在https://github.com/spicyShrimp/iOS-11-UINavigationItem-SXFixSpace这个项目中是没有问题的，请问有遇到吗？

**Comment by lahala** [comment]
在11.2上leftBarButtonItem 还是有问题！！

**Comment by spicyShrimp** [comment]
我这边11.2跑是没有这个问题的,能具体描述一下吗?间距?是指leftBar上有多个按钮的间距还是单个left距离最左边的间距?
