### ISSUE TITLE
点击进入相册，页面弹出时，右上角 Cancel 按钮有一个向左移动的过程

### ISSUE THREAD

**Issue by wayone** [spicyShrimp/UINavigation-SXFixSpace#6]
真机 iPhone 6，10.3.3

**Comment by spicyShrimp** [comment]
具体可以写一个demo给我看看,我这边没有复现这样的情况

**Comment by yfxiarigit** [comment]
可以在viewDidLoad的时候设置忽略偏移

- (void)wa_viewDidLoad {
    if ([self isKindOfClass:[UIImagePickerController class]]) {
        wa_tempDisableFixSpace = wa_disableFixSpace;
        wa_disableFixSpace = YES;
    }
}

//-(void)wa_viewWillAppear:(BOOL)animated {
//    if ([self isKindOfClass:[UIImagePickerController class]]) {
//        wa_tempDisableFixSpace = wa_disableFixSpace;
//        wa_disableFixSpace = YES;
//    }
//    [self wa_viewWillAppear:animated];
//}

**Comment by wayone** [comment]
@spicyShrimp 我运行的你的 demo, 真机 iPhone 6，10.3.3

**Comment by Brances** [comment]
真机iphone7  iOS 10.0.3运行demo后也出现cancel按钮偏移情况~

**Comment by spicyShrimp** [comment]
那是系统相册,本身的位置就应该在那个地方,如果也想要指定位置,我重新出一个版本吧
