### ISSUE TITLE
能否支持pod呢？

### ISSUE THREAD

**Issue by ArthurCL** [spicyShrimp/UINavigation-SXFixSpace#7]
项目中免不了需要用到第三方，用pod导入的，这样后面好维护项目

**Comment by spicyShrimp** [comment]
已经添加到了pod
 🎉  Congrats

 🚀  UINavigation-SXFixSpace (1.0.3) successfully published
 📅  April 19th, 23:00
 🌎  https://cocoapods.org/pods/UINavigation-SXFixSpace
 👍  Tell your friends!

**Comment by ArthurCL** [comment]
终端搜索不到

**Comment by spicyShrimp** [comment]
刚刚添加完成 估计还需要等等

**Comment by ArthurCL** [comment]
谢谢，可以pod install了，pod search 搜索不到而已

**Comment by ArthurCL** [comment]
UIBarButtonItem+SXCreate设置导航栏按钮的 好像没有添加到pod  没看到这个类

**Comment by spicyShrimp** [comment]
该类只是一个扩展类 方便创建UIBarButtonItem而已  不属于修正位置的内容,我就移除了 你可以自己添加进去使用

**Comment by spicyShrimp** [comment]
搜索不到的话
终端输入rm ~/Library/Caches/CocoaPods/search_index.json
删除成功后再执行pod search XXX
由于缓存导致,清除一下缓存  重新搜索即可

**Comment by ArthurCL** [comment]
确实可以，谢谢
