### ISSUE TITLE
导致iOS11以下系统setTitleTextAttributes方法无效

### ISSUE THREAD

**Issue by luzsyn** [spicyShrimp/UINavigation-SXFixSpace#8]
iOS11系统此方法正常，iOS11系统以下：
 [self.navigationItem.rightBarButtonItem setTitleTextAttributes:@{NSFontAttributeName: [UIFont systemFontOfSize:15], NSForegroundColorAttributeName : [UIColor whiteColor]} forState:UIControlStateNormal];
设置无效

**Comment by spicyShrimp** [comment]
这是肯定的,iOS7-11采用的是通用的修正方式, rightBarButtonItem实际会调用rightBarButtonItems来作为导航栏按钮(会多一个占位的按钮),而原来的rightBarButtonItem实际是nil 所以直接设置他是无效的
你可以选择在setRightBarButtonItem之前将按钮定义好即可
