### ISSUE TITLE
rightBarButtonItem 的间距变得特别小

### ISSUE THREAD

**Issue by yasencoder** [spicyShrimp/UINavigation-SXFixSpace#9]
leftBarButtonItem 的距离左边的距离是消除掉了，但是leftBarButtonItem距离右边的边距变得很小了

**Comment by spicyShrimp** [comment]
可以给我发一个截图78268731@qq.com

**Comment by kalezhou** [comment]
这个在iOS11之前的系统上有一个问题，比如新建一个  UIBarButtonItem *barNext = .........，
self.navigationItem.rightBarButtonItem = barNext; 后面再 写 [self.navigationItem.rightBarButtonItem setTextItemEnable:YES]; 这时 self.navigationItem.rightBarButtonItem 获取到的是另外一个BarItem,
self.navigationItem.rightBarButtonItems[1] 才是 上面的barNext

**Comment by spicyShrimp** [comment]
iOS11 之前是将rightBarButtonItem转移到了rightBarButtonItems中 通过一个负值宽度的item来实现偏移，所以原来的rightBarButtonItem就变成了item[1] 这个可以通过原来看到，我没有重载rightBarButtonItem 这个get方法，如果需要的话 ，是可以重新该方法来返回你需要的item的
